pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('jenkins-auth')
  }
     
    stages {
              stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/kalkirs/gcp-devops.git'
            }
        }
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
		    sh 'cd google-compute-engine'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
	{
        sh 'ls -ltr'
	sh 'pwd'
        sh 'gcloud auth activate-service-account jenkins@murthyuat.iam.gserviceaccount.com --key-file=jenkins.json'
	
    }
    }
	}
 	 
	stage('Create vm instance') {
	 steps {
    
        sh 'gcloud compute instances create kalkivm --zone=us-central1-a'
    }
    }
    
    stage('Get creds from GKE cluster') {
	 steps {
    
        sh 'gcloud container clusters get-credentials gke-cluster --zone europe-central2-a --project murthylab'
    }
    }
    
}
}
