pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
              stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/kalkirs/gcp-devops.git'
            }
        }
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
		    sh 'cd google-compute-engine'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
	{
        sh 'ls -ltr'
	sh 'pwd'
        sh 'gcloud auth activate-service-account jenkins@murthylab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
	}
 	 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create pipeline-kalki1 --zone=us-central1-a --machine-type=n1-standard-1 --tags=http-server --create-disk=auto-delete=yes,boot=yes,device-name=commandline-kalki,image=projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20221018,mode=rw,size=10,type=projects/murthylab/zones/europe-west2-a/diskTypes/pd-balanced --metadata-from-file=startup-script=./google-compute-engine/startup-script.sh'
        
    }
    }
}
}
